src/business_controllers/CustomerController.java
package business_controllers;

import helpers.DBConnectionHelper;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import utils.ChangesStatus;

import models.Customer;
import models.MapAccountCustomer;
import dao.CustomerDAO;
import dao.DAOFactory;
import dao.MapAccountCustomerDAO;
import exceptions.NotFoundException;

public class CustomerController {

	public CustomerController() {

	}

	public List<Customer> getCustomers() {
		Connection connection = DBConnectionHelper.getConnection();
		CustomerDAO customerDAO = DAOFactory.getCustomerDAO();
		try {
			return customerDAO.loadAll(connection);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				connection.close();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		return null;
	}

	public Customer getCustomer(int customer_id) throws NotFoundException,
			SQLException {
		
		Customer customer = new Customer();
		CustomerDAO customerDAO = DAOFactory.getCustomerDAO();

		Connection connection = DBConnectionHelper.getConnection();

		try {
			customer = customerDAO.getObject(connection, customer_id);

			MapAccountCustomer map = new MapAccountCustomer();
			map.setCustomer_id(customer.getCustomer_id());

			MapAccountCustomerDAO mapAccountCustomerDAO = DAOFactory
					.getMapAccountCustomerDAO();
			List<MapAccountCustomer> relation = mapAccountCustomerDAO
					.searchMatching(connection, map);

			if (relation.size() < 1) {
				return customer;
			}

			AccountController accountController = new AccountController();
			for (MapAccountCustomer r : relation) {
				customer.addAccount(accountController.getAccountDetails(r
						.getAccount_id()));
			}

			return customer;
		} catch (NotFoundException e) {
			throw new NotFoundException("Custommer do not found");
		} catch (SQLException e) {
			throw new SQLException("SQL Query Exception");
		} finally {
			connection.close();
		}

	}

	/*
	 * public Customer getCustomerDetails(int customer_id) throws
	 * NotFoundException, SQLException{
	 * 
	 * Customer customer = getCustomer(customer_id);
	 * 
	 * Connection connection = DBConnectionHelper.getConnection();
	 * 
	 * //Finding the accounts MapAccountCustomerDAOImpl mapAccountCustomerDAO =
	 * new MapAccountCustomerDAOImpl(); AccountDAOImpl accountDAO = new
	 * AccountDAOImpl();
	 * 
	 * MapAccountCustomer mapAccountCustomer = new MapAccountCustomer();
	 * mapAccountCustomer.setCustomer_id(customer.getCustomer_id());
	 * List<MapAccountCustomer> relation; try { relation =
	 * mapAccountCustomerDAO.searchMatching(connection, mapAccountCustomer);
	 * 
	 * AccountController accountController = new AccountController();
	 * 
	 * //Adding the account(s) CustomerDAOImpl customerDAOImpl = new
	 * CustomerDAOImpl(); for(MapAccountCustomer r : relation){ Account a =
	 * accountController.getAccountDetails(r.getAccount_id());
	 * customer.addAccount(a); }
	 * 
	 * 
	 * 
	 * return customer; } catch (SQLException e) { // TODO Auto-generated catch
	 * block e.printStackTrace(); } finally { connection.close(); }
	 * 
	 * return null; }
	 */

	public ChangesStatus saveCustomer(Customer customer) {
		CustomerDAO customerDAO = DAOFactory.getCustomerDAO();

		Connection connection = DBConnectionHelper.getConnection();
		try {
			if (customer.getCustomer_id() > 0) {
				customerDAO.save(connection, customer);
				connection.commit();
				return new ChangesStatus(true, "Customer successfully saved.");
			} else {
				customerDAO.create(connection, customer);
				connection.commit();
				return new ChangesStatus(true, "Customer successfully created.");
			}
		} catch (SQLException e) {
			e.printStackTrace();
			return new ChangesStatus(false, "Customer can not be save.");
		} catch (NotFoundException e) {
			e.printStackTrace();
			return new ChangesStatus(false, "Customer can not be save.");
		} finally {
			try {
				connection.close();
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
	}

	public ChangesStatus deleteCustomer(int customer_id) {

		return null;
	}

}

WebContent/jsp/admin/account_details.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<h3>
	Details of Account ID ${data.account_id}
	<a href="${page.url_host}${page.url_apppath}admin/account/edit/${data.account_id}"
		style="margin-top: 15px;" class="pull-right btn btn-small btn-info">Edit
		Account</a>
	<a href="${page.url_host}${page.url_apppath}admin/account/transaction/${data.account_id}"
		style="margin-top: 15px;margin-right:20px;" class="pull-right btn btn-small">View Transactions</a>
</h3>

<table class="table">
	<tr>
		<td>Account ID</td>
		<td>${data.account_id}</td>
	</tr>
	<tr>
		<td>Balance</td>
		<td><fmt:formatNumber value="${data.amount}" type="currency"/></td>
	</tr>
	<tr>
		<td>Account Type</td>
		<td><c:choose>
				<c:when test="${data.account_type ==1 }">
								Checking Account
							</c:when>
				<c:when test="${data.account_type == 2 }">
								Saving Account
							</c:when>
			</c:choose></td>
	</tr>
</table>

<h3>Customers own to this Account</h3>
<table class="table table-hover">
	<thead>
		<tr>
			<td>Customer ID</td>
			<td>Name</td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<c:forEach items="${data.customers}" var="_customer">
			<tr>
				<td>${_customer.customer_id}</td>
				<td><b style="font-size: 15px;">${_customer.givenname}</b><br />${_customer.username}
				</td>
				<td><a
					href="${page.url_host}${page.url_apppath}admin/customer/details/${_customer.customer_id}"
					class="btn btn-small">View Details</a></td>
			</tr>
		</c:forEach>
	</tbody>
</table>

WebContent/jsp/admin/account_edit.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<script type="text/javascript">
	
	$(document).ready(function(){
		$("#addRowBtn").click(function(){
			$("#newowners").append('<input type="text" name="customer_ids" autocomplete="off" placeholder="Customer ID" /><br />');
		});
	});
	
</script>

<c:choose>
	<c:when test="${data.account_id > 0 }">
		<h3>
			Edit : Account ID
			<c:if test="${data.account_id > 0}">${data.account_id}</c:if>
			<a
				href="${page.url_host}${page.url_apppath}admin/account/details/${data.account_id}"
				class="btn btn-small btn-info pull-right" style="margin-top: 15px;">
				View Details of this Account</a>
		</h3>
	</c:when>
	<c:otherwise>
		<h3>New Account</h3>
	</c:otherwise>
</c:choose>

<form name="form-customer" id="form-customer"
	action="${page.url_host}${page.url_apppath}admin/post/save_account"
	method="post">
	<table class="table">
		<tr>
			<td>Account ID</td>
			<td><input type="text" disabled="disabled"
				value="<c:if test="${data.account_id > 0}">${data.account_id}</c:if>" />
				<input type="hidden" name="account_id"
				value="<c:if test="${data.account_id > 0}">${data.account_id}</c:if>" />
			</td>
		</tr>
		<tr>
			<td>Ownership</td>
			<td><c:forEach items="${data.customers}" var="_customer">
					<input disabled="disabled" type="text" style="width: 80px"
						value="${_customer.customer_id}" /> &nbsp;${_customer.givenname} (ID : ${_customer.customer_id})
				<input name="customer_ids" type="hidden"
						value="${_customer.customer_id}" /><br />
				</c:forEach>
				<div id="newowners">
				
				</div>
				<input type="button" id="addRowBtn" value="Add Owner" class="btn btn-small btn-info" />  
			</td>
		</tr>
		<tr>
			<td>Security PIN</td>
			<td><input
				value="<c:if test="${data.pin != 0}">${data.pin}</c:if>" name="pin" autocomplete="off"
				type="text" placeholder="Security Pin" /></td>
		</tr>
		<tr>
			<td>Amount</td>
			<td><input
				value="<c:if test="${data.amount != ''}">${data.amount}</c:if>"
				name="amount" type="text" placeholder="Amount" autocomplete="off" /></td>
		</tr>
		<tr>
			<td>Account Type</td>
			<td><select name="account_type" placeholder="Account Type">
					<option value="">- Select One -</option>
					<option
						<c:if test="${data.account_type == 1}">selected="selected"</c:if>
						value="1">Checking Account</option>
					<option
						<c:if test="${data.account_type == 2}">selected="selected"</c:if>
						value="2">Saving Account</option>
			</select></td>
		</tr>
		<tr>
			<td>Bank Branch</td>
			<td><input name="bank_branch_id" type="text"
				value="<c:if test="${data.bank_branch_id > 0}">${data.bank_branch_id}</c:if>"
				placeholder="Bank Branch ID" /></td>
		</tr>
		<tr>
			<td><a class="btn btn-primary btn-large"
				href="${page.url_host}${page.url_apppath}admin/dashboard">Cancel</a></td>
			<td><input class="btn btn-primary btn-large" type="submit"
				value="Submit" /></td>
		</tr>
	</table>
</form>

WebContent/jsp/admin/account_search.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<h3>Search Bank Account</h3>
<hr />
<form
	action="${page.url_host}${page.url_apppath}admin/post/search_account"
	method="post" name="form-account" class="form-search">
	<input type="text" autocomplete="off" name="account_id" class="input-medium search-query"
		placeholder="Bank Account ID" style="width: 250px" /> &nbsp;&nbsp;
	<button type="submit" class="btn btn-primary">Search</button>
</form>

WebContent/jsp/admin/account_transaction.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<h4>Transaction History Showing for Account Id -
	${account_id}</h4>
<table class="table table-hover table table-striped">
	<thead>
		<tr>
			<td>Transaction Time</td>
			<td>Amount</td>
			<td>Type</td>
		</tr>
	</thead>
	<tbody>
		<c:forEach items="${data}" var="history">
			<tr>
				<td><fmt:formatDate value="${history.transaction_time}" pattern="MM/d/yyyy - hh:mm" /></td>
				<td><fmt:formatNumber value="${history.transaction_amount}" type="currency"/></td>
				<td><c:choose>
						<c:when test="${history.transaction_type == 1}">
							Deposit
						</c:when>
						<c:when test="${history.transaction_type == 2}">
							Withdraw
						</c:when>
						<c:when test="${history.transaction_type == 3}">
							<c:choose>
								<c:when test="${history.transaction_relation_type == 1}">
									Sent to Account ID - ${history.transaction_relation_account_id}
								</c:when>
								<c:when test="${history.transaction_relation_type == 2}">
									Receive from Account ID - ${history.transaction_relation_account_id}
								</c:when>
								<c:otherwise>&nbsp;</c:otherwise>
							</c:choose>
						</c:when>
						<c:otherwise>Unknown Transaction</c:otherwise>
					</c:choose></td>
			</tr>
		</c:forEach>
	</tbody>
</table>

WebContent/jsp/admin/bank_branch_edit.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>



<form name="form-customer" id="form-customer"
	action="${page.url_host}${page.url_apppath}admin/post/save_bank_branch"
	method="post">
	<table class="table">
		<tr>
			<td>Branch ID</td>
			<td><input type="text" disabled="disabled"
				value="<c:if test="${data.bank_branch_id > 0}">${data.bank_branch_id}</c:if>" />
				<input name="bank_branch_id" type="hidden"
				value="<c:if test="${data.bank_branch_id > 0}">${data.bank_branch_id}</c:if>" />
			</td>
		</tr>
		<tr>
			<td>Branch Name</td>
			<td><input value="${data.name}" name="name" type="text" autocomplete="off"
				required="required" placeholder="Branch Name" /></td>
		</tr>
		<tr>
			<td>Branch Location</td>
			<td><textarea name="location" type="textarea" autocomplete="off"
					required="required" placeholder="Description">${data.location}</textarea></td>
		</tr>
		<tr>
			<td>Description</td>
			<td><textarea name="description" type="textarea"
					required="required" placeholder="Description">${data.description}</textarea></td>
		</tr>
		<tr>
			<td><a class="btn btn-primary btn-large"
				href="${page.url_host}${page.url_apppath}admin/bank_branch/list">Cancel</a></td>
			<td><input class="btn btn-primary btn-large" type="submit"
				value="Submit" /></td>
		</tr>
	</table>
</form>

WebContent/jsp/admin/bank_branch_list.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<h3>Bank Branch List</h3>

<table class="table">
	<thead>
		<th>ID</th>
		<th>Name</th>
		<th>Location</th>
		<th>Description</th>
		<th></th>
	</thead>
	<tbody>
		<c:forEach items="${data}" var="bank_branch">
			<tr>
				<td>${bank_branch.bank_branch_id}</td>
				<td>${bank_branch.name}</td>
				<td>${bank_branch.location}</td>
				<td>${bank_branch.description}</td>
				<td><a class="btn btn-small" style="width: 50px;"
					href="${page.url_host}${page.url_apppath}admin/bank_branch/edit/${bank_branch.bank_branch_id}">Edit</a>
				</td>
			</tr>
		</c:forEach>
	</tbody>
</table>

WebContent/jsp/admin/customer_details.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<h3>
	Detail Information of ${data.givenname} &nbsp;&nbsp;&nbsp;<a
		href="${page.url_host}${page.url_apppath}admin/customer/edit/${data.customer_id}"
		style="margin-top: 15px;" class="pull-right btn btn-small btn-info">Edit
		Details</a>
</h3>

<table class="table">
	<tr>
		<td>Customer ID</td>
		<td>${data.customer_id}</td>
	</tr>
	<tr>
		<td>NRIC Number</td>
		<td>${data.nric}</td>
	</tr>
	<tr>
		<td>Username</td>
		<td>${data.username}</td>
	</tr>
	<tr>
		<td>Given Name</td>
		<td>${data.givenname}</td>
	</tr>
	<tr>
		<td>Address</td>
		<td>${data.address}</td>
	</tr>
	<tr>
		<td>Gender</td>
		<td>${data.gender}</td>
	</tr>
	<tr>
		<td>Nationality</td>
		<td>${data.nationality}
	</tr>
	<tr>
		<td>Date of Birth</td>
		<td>
		<fmt:formatDate value="${data.date_of_birth}" pattern="MM/d/yyyy" />
		</td>
	</tr>
	<tr>
		<td>Date of Join</td>
		<td><fmt:formatDate value="${data.date_of_join}" pattern="MM/d/yyyy" /></td>
	</tr>
</table>
<c:if test="${not empty data.accounts}">
	<h3>Bank Accounts Owned by Customer</h3>
	<table class="table table-hover">
		<thead>
			<tr>
				<td>Account ID</td>
				<td>Balance</td>
				<td>Account Type</td>
				<td>Ownership</td>
				<td></td>
			</tr>
		</thead>
		<tbody>
			<c:forEach items="${data.accounts}" var="_account">
				<tr>
					<td>${_account.account_id}</td>
					<td><fmt:formatNumber value="${_account.amount}" type="currency"/></td>
					<td><c:choose>
							<c:when test="${_account.account_type == 1 }">Checking Account </c:when>
							<c:when test="${_account.account_type == 2 }">Saving Account </c:when>
							<c:otherwise> Undefined </c:otherwise>
						</c:choose></td>
					<td><c:choose>
							<c:when test="${_account.joint_account == false }">Single Account</c:when>
							<c:otherwise> Joint Account </c:otherwise>
						</c:choose> <c:if test="${_account.joint_account == true }">
							<br />
							<u>Owners</u>
							<ul>
								<c:forEach items="${_account.customers}" var="_customer">
									<li><a
										href="${page.url_host}${page.url_apppath}admin/customer/details/${_customer.customer_id}">${_customer.givenname}</a></li>
								</c:forEach>
							</ul>
						</c:if></td>
					<td><a
						href="${page.url_host}${page.url_apppath}admin/account/details/${_account.account_id}"
						class="btn btn-small">View Details</a></td>
				</tr>
			</c:forEach>
		</tbody>
	</table>
</c:if>

WebContent/jsp/admin/customer_list.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<table class="table table-hover">
	<thead>
		<th>Customer ID</th>
		<th>Name / Username</th>
		<th>NRIC</th>
		<th></th>
	</thead>
	<tbody>
		<c:forEach items="${data}" var="customer">
			<tr>
				<td>${customer.customer_id}</td>
				<td><b style="font-size: 18px;">${customer.givenname}</b><br />
					<span class="list-username">${customer.username}</span></td>
				<td>${customer.nric}</td>
				<td><a class="btn btn-small"
					style="width: 50px; margin-bottom: 5px;"
					href="${page.url_host}${page.url_apppath}admin/customer/edit/${customer.customer_id}">Edit</a><br />
					<a class="btn btn-small" style="width: 50px;"
					href="${page.url_host}${page.url_apppath}admin/customer/details/${customer.customer_id}">Details</a>
				</td>
			</tr>
		</c:forEach>
	</tbody>
</table>

WebContent/jsp/admin/customer_search.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<h3>Search Customer</h3>
<hr />
<form
	action="${page.url_host}${page.url_apppath}admin/post/search_customer"
	method="post" name="form-customer" class="form-search">
	<input type="text" name="customer_id" class="input-medium search-query" autocomplete="off"
		placeholder="Customer ID" style="width: 250px" /> &nbsp;&nbsp;
	<button type="submit" class="btn btn-primary">Search</button>
</form>

WebContent/jsp/admin/dashboard.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<div id="dashboard">
	<div class="row">
		<a href="${page.url_host}${page.url_apppath}admin/customer/new"
			class="span4""> <img class="img-circle"
			src="${page.url_assets}images/user_add.png" style="width: 120px;" />
			<br />
		<h5>New Customer Account</h5>
		</a> <a href="${page.url_host}${page.url_apppath}admin/customer/search"
			class="span4""> <img class="img-circle"
			src="${page.url_assets}images/user_search.png" style="width: 120px;" />
			<br />
		<h5>Search Customer Account</h5>
		</a>
	</div>
	<div class="row">
		<a href="${page.url_host}${page.url_apppath}admin/account/new"
			class="span4"> <img src="${page.url_assets}images/new_file.png"
			style="width: 80px;" /> <br />
		<h5>New Bank Account</h5>
		</a> <a href="${page.url_host}${page.url_apppath}admin/account/search"
			class="span4"> <img src="${page.url_assets}images/search.png"
			style="width: 80px;" /> <br />
		<h5>Search Bank Account</h5>
		</a>

	</div>
</div>